# Social Media analysis

In [1]:
# Firstly, we will need to import all the required libraries to proceed with the data analysis
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
# We will also need to import the libraries for the unsupervised learning 
from sklearn.impute import KNNImputer 
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans

In [4]:
# Reading in the data file using 
data = pd.read_csv('social_media_user_behavior.csv')
data.head()

,user_id,age,gender,country,profession,primary_platform,platforms_used_count,daily_usage_hours,sessions_per_day,avg_session_duration_min,...,primary_purpose,sleep_disruption,self_reported_mental_health_score,screen_time_concern,notification_frequency,privacy_setting,influencer_status,account_join_date,mood_while_scrolling,takes_social_media_breaks
0,USR00001,30,Female,UK,Doctor,Facebook,1,1.6,2,48.0,...,Entertainment,No impact,3.9,No,Do Not Disturb,Friends Only,No,2022-10-21,Neutral,No
1,USR00002,25,Male,USA,Entrepreneur,Instagram,2,2.4,5,28.8,...,News & Updates,Moderate impact,4.2,No,Selected,Public,No,2024-12-03,Neutral,Yes
2,USR00003,32,Male,UAE,Freelancer,TikTok,5,0.5,6,5.0,...,Learning,Mild impact,4.8,Yes,Always On,Friends Only,No,2023-03-29,Happy,Yes
3,USR00004,39,Prefer not to say,Pakistan,Other,TikTok,4,3.0,7,25.7,...,Entertainment,Mild impact,7.9,Somewhat,Always On,Public,Yes,2024-04-26,Happy,No
4,USR00005,25,Male,UK,Other,YouTube,3,3.9,7,33.4,...,Entertainment,Mild impact,6.5,No,Do Not Disturb,Public,No,2023-09-08,Inspired,No

In [5]:
# Getting all the data information
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 34 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   user_id                            2000 non-null   str
 1   age                                2000 non-null   int64
 2   gender                             2000 non-null   str
 3   country                            2000 non-null   str
 4   profession                         2000 non-null   str
 5   primary_platform                   2000 non-null   str
 6   platforms_used_count               2000 non-null   int64
 7   daily_usage_hours                  2000 non-null   float64
 8   sessions_per_day                   2000 non-null   int64
 9   avg_session_duration_min           2000 non-null   float64
 10  preferred_device                   2000 non-null   str
 11  peak_usage_time                    2000 non-null   str
 12  followers_count                    2000 non-null   int64
 13  following_count                    2000 non-null   int64
 14  posts_per_week                     2000 non-null   int64
 15  likes_given_per_day                2000 non-null   int64
 16  comments_per_day                   2000 non-null   int64
 17  shares_per_day                     2000 non-null   int64
 18  dms_sent_per_day                   2000 non-null   int64
 19  preferred_content_type             2000 non-null   str
 20  scroll_speed                       2000 non-null   str
 21  ad_click_rate                      2000 non-null   float64
 22  purchased_via_social_media         2000 non-null   str
 23  monthly_spend_via_social_usd       2000 non-null   float64
 24  primary_purpose                    2000 non-null   str
 25  sleep_disruption                   2000 non-null   str
 26  self_reported_mental_health_score  2000 non-null   float64
 27  screen_time_concern                2000 non-null   str
 28  notification_frequency             2000 non-null   str
 29  privacy_setting                    2000 non-null   str
 30  influencer_status                  2000 non-null   str
 31  account_join_date                  2000 non-null   str
 32  mood_while_scrolling               2000 non-null   str
 33  takes_social_media_breaks          2000 non-null   str
dtypes: float64(5), int64(10), str(19)
memory usage: 820.0 KB

In [7]:
# Getting different columns to have a clearer picture of the data scope
data.columns

Index(['user_id', 'age', 'gender', 'country', 'profession', 'primary_platform',
       'platforms_used_count', 'daily_usage_hours', 'sessions_per_day',
       'avg_session_duration_min', 'preferred_device', 'peak_usage_time',
       'followers_count', 'following_count', 'posts_per_week',
       'likes_given_per_day', 'comments_per_day', 'shares_per_day',
       'dms_sent_per_day', 'preferred_content_type', 'scroll_speed',
       'ad_click_rate', 'purchased_via_social_media',
       'monthly_spend_via_social_usd', 'primary_purpose', 'sleep_disruption',
       'self_reported_mental_health_score', 'screen_time_concern',
       'notification_frequency', 'privacy_setting', 'influencer_status',
       'account_join_date', 'mood_while_scrolling',
       'takes_social_media_breaks'],
      dtype='str')

In [8]:
# Getting descriptive data for the numerical values
data.describe()

,age,platforms_used_count,daily_usage_hours,sessions_per_day,avg_session_duration_min,followers_count,following_count,posts_per_week,likes_given_per_day,comments_per_day,shares_per_day,dms_sent_per_day,ad_click_rate,monthly_spend_via_social_usd,self_reported_mental_health_score
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2.000000e+03,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.00000
mean,26.986000,3.010000,2.990650,5.024500,47.547400,4.153738e+03,513.9985,2.964000,19.883000,3.991500,1.988500,8.02600,0.130048,22.618225,6.17115
std,7.649775,1.431756,1.858501,2.249985,51.104393,4.793563e+04,851.8179,1.679915,4.389527,1.997354,1.413636,2.77618,0.094675,33.884331,1.74912
min,13.000000,1.000000,0.500000,1.000000,3.300000,0.000000e+00,4.0000,0.000000,6.000000,0.000000,0.000000,1.00000,0.001000,0.000000,1.00000
25%,22.000000,2.000000,1.600000,3.000000,18.975000,2.017500e+02,109.0000,2.000000,17.000000,3.000000,1.000000,6.00000,0.058750,0.000000,4.90000
50%,27.000000,3.000000,2.600000,5.000000,34.000000,6.880000e+02,249.0000,3.000000,20.000000,4.000000,2.000000,8.00000,0.108000,7.315000,6.20000
75%,32.000000,4.000000,3.900000,6.000000,56.000000,2.320500e+03,580.0000,4.000000,23.000000,5.000000,3.000000,10.00000,0.182000,33.632500,7.40000
max,57.000000,5.000000,12.000000,15.000000,594.000000,2.110323e+06,10000.0000,10.000000,38.000000,11.000000,8.000000,19.00000,0.585000,266.370000,10.00000

In [10]:
# Now we will proceed to confirming whether there are any missing values in any of the 
# columns
data.notnull().count()

user_id                              2000
age                                  2000
gender                               2000
country                              2000
profession                           2000
primary_platform                     2000
platforms_used_count                 2000
daily_usage_hours                    2000
sessions_per_day                     2000
avg_session_duration_min             2000
preferred_device                     2000
peak_usage_time                      2000
followers_count                      2000
following_count                      2000
posts_per_week                       2000
likes_given_per_day                  2000
comments_per_day                     2000
shares_per_day                       2000
dms_sent_per_day                     2000
preferred_content_type               2000
scroll_speed                         2000
ad_click_rate                        2000
purchased_via_social_media           2000
monthly_spend_via_social_usd         2000
primary_purpose                      2000
sleep_disruption                     2000
self_reported_mental_health_score    2000
screen_time_concern                  2000
notification_frequency               2000
privacy_setting                      2000
influencer_status                    2000
account_join_date                    2000
mood_while_scrolling                 2000
takes_social_media_breaks            2000
dtype: int64